### ISSUE TITLE
[bug] Incorrect view file

### ISSUE THREAD

**Issue by ghost** [OCA/connector-ecommerce#22]
I followed the instructions here to install the magento connector, and it seems to be an issue in this module that is preventing installation.

http://odoo-magento-connector.com/guides/installation_guide.html

I will submit pull request when I resolve.

2015-08-19 16:15:58,707 9671 INFO test8 openerp.modules.loading: loading connector_ecommerce/payment_method_view.xml
2015-08-19 16:15:58,737 9671 ERROR test8 openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/opt/odoo/odoo-server/openerp/http.py", line 537, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo-server/openerp/http.py", line 574, in dispatch
    result = self._call_function(*_self.params)
  File "/opt/odoo/odoo-server/openerp/http.py", line 310, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/service/model.py", line 113, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/http.py", line 307, in checked_call
    return self.endpoint(_a, *_kw)
  File "/opt/odoo/odoo-server/openerp/http.py", line 803, in __call__
    return self.method(_args, *_kw)
  File "/opt/odoo/odoo-server/openerp/http.py", line 403, in response_wrap
    response = f(_args, *_kw)
  File "/opt/odoo/odoo-server/addons/web/controllers/main.py", line 948, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/odoo-server/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/addons/base/module/module.py", line 446, in button_immediate_install
    return self._button_immediate_function(cr, uid, ids, self.button_install, context=context)
  File "/opt/odoo/odoo-server/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/addons/base/module/module.py", line 494, in _button_immediate_function
    registry = openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
  File "/opt/odoo/odoo-server/openerp/modules/registry.py", line 370, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/odoo-server/openerp/modules/loading.py", line 355, in load_modules
    loaded_modules, update_module)
  File "/opt/odoo/odoo-server/openerp/modules/loading.py", line 255, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/opt/odoo/odoo-server/openerp/modules/loading.py", line 176, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/opt/odoo/odoo-server/openerp/modules/loading.py", line 118, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/opt/odoo/odoo-server/openerp/tools/convert.py", line 901, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/opt/odoo/odoo-server/openerp/tools/convert.py", line 987, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/opt/odoo/odoo-server/openerp/tools/convert.py", line 853, in parse
    self._tags[rec.tag](self.cr, rec, n, mode=mode)
  File "/opt/odoo/odoo-server/openerp/tools/convert.py", line 755, in _tag_record
    f_val = self.id_get(cr, f_ref)
  File "/opt/odoo/odoo-server/openerp/tools/convert.py", line 832, in id_get
    res = self.model_id_get(cr, id_str, raise_if_not_found)
  File "/opt/odoo/odoo-server/openerp/tools/convert.py", line 843, in model_id_get
    raise_if_not_found=raise_if_not_found)
  File "/opt/odoo/odoo-server/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/addons/base/ir/ir_model.py", line 936, in xmlid_to_res_model_res_id
    return self.xmlid_lookup(cr, uid, xmlid)[1:3]
  File "/opt/odoo/odoo-server/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "<string>", line 2, in xmlid_lookup
  File "/opt/odoo/odoo-server/openerp/tools/cache.py", line 74, in lookup
    value = d[key] = self.method(_args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/addons/base/ir/ir_model.py", line 926, in xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % (xmlid))
ParseError: "External ID not found in the system: sale_payment_method_automatic_workflow.payment_method_view_form" while parsing /home/oca/connector-ecommerce/connector_ecommerce/payment_method_view.xml:12, near
<record id="payment_method_view_form" model="ir.ui.view">
            <field name="name">payment.method.connector_ecommerce.form</field>
            <field name="model">payment.method</field>
            <field name="inherit_id" ref="sale_payment_method_automatic_workflow.payment_method_view_form"/>
            <field name="arch" type="xml">
                <group name="general" position="after">
                    <group name="import_rule" string="Import Rules">
                        <group>
                            <field name="import_rule"/>
                            <field name="days_before_cancel"/>
                        </group>
                        <group name="import_rule_help" class="oe_grey" col="1">
                            <p attrs="{'invisible': [('import_rule', '!=', 'never')]}">
                                The sales orders using the payment method will never be imported.
                            </p>
                            <p attrs="{'invisible': [('import_rule', '!=', 'always')]}">
                                The sales orders using the payment method will always be imported.
                            </p>
                            <p attrs="{'invisible': [('import_rule', '!=', 'paid')]}">
                                The sales orders using the payment method will be imported
                                only when they receive a payment on the E-Commerce backend.<br/>
                            </p>
                        </group>
                    </group>
                </group>
            </field>
        </record>

**Comment by ghost** [comment]
Another module was causing conflict
